// Specter — agent identity registry
// Each agent has color, icon, label, role description.

import {
  BarChart3,
  LineChart,
  MessageCircle,
  Newspaper,
  TrendingUp,
  TrendingDown,
  Shield,
} from 'lucide-react';

export const AGENTS = [
  {
    id: 'fundamentals',
    name: 'Fundamentals Analyst',
    icon: BarChart3,
    emoji: '📊',
    color: 'hsl(189 100% 50%)',
    colorClass: 'text-specter-primary',
    bgClass: 'bg-specter-primary/10',
    borderClass: 'border-specter-primary/30',
    role: 'Earnings, valuation, balance sheet',
  },
  {
    id: 'technical',
    name: 'Technical Analyst',
    icon: LineChart,
    emoji: '📈',
    color: 'hsl(186 92% 70%)',
    colorClass: 'text-cyan-300',
    bgClass: 'bg-cyan-500/10',
    borderClass: 'border-cyan-500/30',
    role: 'Price action, indicators, key levels',
  },
  {
    id: 'sentiment',
    name: 'Sentiment Analyst',
    icon: MessageCircle,
    emoji: '💬',
    color: 'hsl(271 91% 65%)',
    colorClass: 'text-specter-purple',
    bgClass: 'bg-[hsl(271_91%_65%/0.1)]',
    borderClass: 'border-[hsl(271_91%_65%/0.3)]',
    role: 'Social mood, retail sentiment',
  },
  {
    id: 'news',
    name: 'News Analyst',
    icon: Newspaper,
    emoji: '📰',
    color: 'hsl(24 95% 53%)',
    colorClass: 'text-specter-orange',
    bgClass: 'bg-[hsl(24_95%_53%/0.1)]',
    borderClass: 'border-[hsl(24_95%_53%/0.3)]',
    role: 'Headlines, macro, event risk',
  },
  {
    id: 'bull',
    name: 'Bull Researcher',
    icon: TrendingUp,
    emoji: '🐂',
    color: 'hsl(145 100% 45%)',
    colorClass: 'text-bull',
    bgClass: 'bg-[hsl(145_100%_45%/0.1)]',
    borderClass: 'border-[hsl(145_100%_45%/0.3)]',
    role: 'Long case argument',
  },
  {
    id: 'bear',
    name: 'Bear Researcher',
    icon: TrendingDown,
    emoji: '🐻',
    color: 'hsl(348 100% 54%)',
    colorClass: 'text-bear',
    bgClass: 'bg-[hsl(348_100%_54%/0.1)]',
    borderClass: 'border-[hsl(348_100%_54%/0.3)]',
    role: 'Short / avoid case argument',
  },
  {
    id: 'risk',
    name: 'Risk Manager',
    icon: Shield,
    emoji: '🛡️',
    color: 'hsl(41 100% 50%)',
    colorClass: 'text-caution',
    bgClass: 'bg-[hsl(41_100%_50%/0.1)]',
    borderClass: 'border-[hsl(41_100%_50%/0.3)]',
    role: 'Risk score, sizing, final verdict',
  },
];

export const VERDICT_STYLES = {
  'Strong Buy': {
    bg: 'bg-[hsl(145_100%_45%/0.15)]',
    text: 'text-bull',
    border: 'border-[hsl(145_100%_45%/0.4)]',
    dot: 'bg-bull',
  },
  Buy: {
    bg: 'bg-[hsl(145_70%_45%/0.1)]',
    text: 'text-[hsl(145_85%_60%)]',
    border: 'border-[hsl(145_70%_45%/0.3)]',
    dot: 'bg-[hsl(145_70%_55%)]',
  },
  Hold: {
    bg: 'bg-[hsl(41_100%_50%/0.1)]',
    text: 'text-caution',
    border: 'border-[hsl(41_100%_50%/0.3)]',
    dot: 'bg-caution',
  },
  Avoid: {
    bg: 'bg-[hsl(348_80%_54%/0.1)]',
    text: 'text-[hsl(348_85%_65%)]',
    border: 'border-[hsl(348_80%_54%/0.3)]',
    dot: 'bg-[hsl(348_80%_60%)]',
  },
  'Strong Avoid': {
    bg: 'bg-[hsl(348_100%_54%/0.15)]',
    text: 'text-bear',
    border: 'border-[hsl(348_100%_54%/0.4)]',
    dot: 'bg-bear',
    pulse: true,
  },
};